<a href="https://colab.research.google.com/github/issarbhavya/ML/blob/main/00_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### tf.constant()

In [2]:
import tensorflow as tf
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of our vector tensor
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [9]:
tensor.ndim

3

scalar: a single number.

vector: a number with direction (e.g. wind speed with direction).

matrix: a 2-dimensional array of numbers.

tensor: an n-dimensional arrary of numbers
bold text(where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector). 


### tf.variable()


In [10]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [11]:
# To change an element of a tf.Variable() tensor requires the assign() method.

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [12]:
# Will error (can't change tf.constant())


# unchangeable_tensor[0].assign(7)
# unchangleable_tensor

### Random


In [13]:
random_1 = tf.random.Generator.from_seed(42) 
# set the seed for reproducibility (here we can use any number)

random_1 = random_1.normal(shape=(3, 2))
# create tensor from a normal distribution
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [14]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [15]:
random_1 == random_2
## since both are generated from the same root, i.e. that is same number
## so, all the values generated for a same shape will be equal

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [16]:
# Create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Check the tensors and see if they are equal
random_3, random_4, random_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

---


NOTE :

When neural network starts to learn, it learns patterns is some form of datasets,

it starts off with random patterns nd slowly adjusts them as it continuously learn from more and more examples




---



### Shuffle order of elements in tensor

In [17]:
# Shuffle a tensor. it's valuable to shuffle your data, so that the module can be best trained

not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [18]:
# Gets different results each time

m1=tf.random.shuffle(not_shuffled)
m2=tf.random.shuffle(not_shuffled)

m1,m2

## the following shufles the tensor along its first dimension only

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 2,  5],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 3,  4],
        [ 2,  5],
        [10,  7]], dtype=int32)>)


As you can see, the dimension is 3,2 i.e  3 rows and 2 columns so, shuffeling

was done along first dimension only which was, rows

---



In [42]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)

tf.random.shuffle(not_shuffled, seed=42)

## even if seed is given, still the arrangement after shuffling will be different 
## (here seed is "operation seed" )

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [45]:
## This will Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

tf.random.set_seed(42) sets the global seed, and the seed parameter in tf.

random.shuffle(seed=42) sets the operation seed.

In [30]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results
"""The above line will not return any value, it sets the global seed"""

# Set the operation random seed
tf.random.shuffle(not_shuffled)

## you can run this several times, still the shuffle pattern will remain the same,
## this is how we use use global random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>